version: '3.2'

services:
  javaspring:
    image: app
    networks:
      - javaspring
      - nodeapp
  nodeapp:
    container_name: 'nodeapp'
    build: .
    restart: always
    ports:
      - '3000:3000'
    networks:
      - nodeapp
      - redis
    environment:
      - DATABASE_URL=http://javaspring:8080/api/v1/GetAll
  redis:
    image: 'bitnami/redis:latest'

    ports:
      - 6379:6379

    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis
networks:
  javaspring:
  nodeapp:
  redis: