version: '3.8'

services:
  nodeapp:
    container_name: 'nodeapp'
    build: .
    restart: always
    ports:
      - '3000:3000'


  redis:
    image: 'bitnami/redis:latest'

    ports:
      - 6379:6379

    environment:
        - ALLOW_EMPTY_PASSWORD=yes
