version: '3.2'

services:
  nodeapp:
    container_name: 'nodeapp'
    build: .
    restart: always
    ports:
      - '3000:3000'
  redis:
    image: 'bitnami/redis:latest'

    ports:
      - 6379:6379

    environment:
        - ALLOW_EMPTY_PASSWORD=yes
networks:
  default:
    external:
      name: external-example